#!/bin/sh

#########################################################################
# This file should aliased in your .bashrc and will not work otherwise. #
### You will also need the SkilStak Colors Module to run this version ###
############# A color-free version will be available "soon" #############
#########################################################################

if [ -f "setup" ] && [ -d "bin" ] && [ -d "src" ]
then
  path=$(pwd)
  . $path/setup
  echo "${c_base01}setup${c_green} has been sourced."
elif [ -d "bin" ] && [ -d "src" ]
then
  echo "${c_red}This will create a new ${c_base01}setup ${c_red}file.\nDo you wish to continue? ${c_reset}[${c_orange}Y${c_reset}/${c_orange}n${c_reset}]"
  printf "${c_blue}>>> ${c_cyan}"
  stty raw
  confirm=$(dd bs=1 count=1 2> /dev/null)
  stty -raw
  if [ "$confirm" != "y" ]
  then
    echo "\n${c_red}The item will not be made."
  else
    path=$(pwd)
    echo "#REMEBER: SOURCE ME, DON'T RUN ME.\n" >> setup
    echo "export GOPATH=${path}" >> setup
    echo "export GOPATH=${path}/bin" >> setup
    echo "export GOPATH=${path}:\$PATH" >> setup
    . $path/setup
    echo "\n${c_base01}setup${c_green} has been created."
    echo "${c_base01}setup${c_green} has been sourced."
  fi
else
  echo "${c_red}This will create a new ${c_base01}setup${c_red}, ${c_base01}bin${c_red}, and ${c_base01}src${c_red}.\nDo you wish to continue? ${c_reset}[${c_orange}Y${c_reset}/${c_orange}n${c_reset}]"
  printf "${c_blue}>>> ${c_cyan}"
  stty raw
  confirm=$(dd bs=1 count=1 2> /dev/null)
  stty -raw
  if [ "$confirm" != "y" ]
  then
    echo "\n${c_red}The items will not be made."
  else
    mkdir src
    mkdir bin
    path=$(pwd)
    echo "#REMEBER: SOURCE ME, DON'T RUN ME.\n" >> setup
    echo "export GOPATH=${path}" >> setup
    echo "export GOPATH=${path}/bin" >> setup
    echo "export GOPATH=${path}:\$PATH" >> setup
    . $path/setup
    echo "\n${c_base01}setup${c_green}, ${c_base01}bin${c_green}, and ${c_base01}src${c_green} has been created."
    echo "${c_base01}setup${c_green} has been sourced."
  fi
fi
